"""querymetrics

Revision ID: 79c754aa927e
Revises: a476ae7234a6
Create Date: 2021-01-29 16:39:48.228525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '79c754aa927e'
down_revision = 'a476ae7234a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('querymetrics',
                    sa.Column('benchmark_id', sa.BIGINT(), nullable=False),
                    sa.Column('batch_id', sa.BIGINT(), nullable=False),
                    sa.Column('starttime', sa.BIGINT(), nullable=False),
                    sa.Column('q1resulttime', sa.BIGINT(), nullable=True),
                    sa.Column('q1latency', sa.BIGINT(), nullable=True),
                    sa.Column('q2resulttime', sa.BIGINT(), nullable=True),
                    sa.Column('q2latency', sa.BIGINT(), nullable=True),
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('querymetrics')
    # ### end Alembic commands ###
