"""latencymeasurements

Revision ID: a476ae7234a6
Revises: 57fe6cb0be0b
Create Date: 2021-01-29 13:31:13.117829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a476ae7234a6'
down_revision = '57fe6cb0be0b'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('latencymeasurement',
                    sa.Column('benchmark_id', sa.BigInteger(), nullable=False),
                    sa.Column('timestamp', postgresql.TIMESTAMP()),
                    sa.Column('avglatency', sa.Float()),
                    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('latencymeasurement')
    # ### end Alembic commands ###
