"""added documentation and example code

Revision ID: b45e34aef7fc
Revises: 867f19f868d7
Create Date: 2020-11-19 17:45:22.800923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b45e34aef7fc'
down_revision = '867f19f868d7'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("INSERT INTO recentchanges (id, timestamp, level, description) VALUES (uuid_generate_v4(), now(), 2, \'added documentation and example code\')")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
