"""add recentchanges table

Revision ID: f7770ad60f31
Revises: efae575c9ad3
Create Date: 2020-10-05 15:21:31.330272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7770ad60f31'
down_revision = 'efae575c9ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recentchanges',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('level', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.execute("INSERT INTO recentchanges (id, timestamp, level, description) VALUES (uuid_generate_v4(), now(), 2, \'added table for recent changes\')")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recentchanges')
    # ### end Alembic commands ###
