"""your migration description

Revision ID: fed3f5bfeb4d
Revises: f7770ad60f31
Create Date: 2020-10-26 16:11:41.295428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fed3f5bfeb4d'
down_revision = 'f7770ad60f31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servermonitormetrics',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('server_name', sa.Unicode(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('load1m', sa.Float(), nullable=True),
    sa.Column('load5m', sa.Float(), nullable=True),
    sa.Column('load15m', sa.Float(), nullable=True),
    sa.Column('mem_total', sa.BigInteger(), nullable=True),
    sa.Column('mem_available', sa.BigInteger(), nullable=True),
    sa.Column('mem_used', sa.BigInteger(), nullable=True),
    sa.Column('mem_free', sa.BigInteger(), nullable=True),
    sa.Column('duration_millis', sa.BigInteger(), nullable=True),
    sa.Column('read_count', sa.BigInteger(), nullable=True),
    sa.Column('write_count', sa.BigInteger(), nullable=True),
    sa.Column('read_bytes', sa.BigInteger(), nullable=True),
    sa.Column('write_bytes', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.execute("INSERT INTO recentchanges (id, timestamp, level, description) VALUES (uuid_generate_v4(), now(), 2, \'Added Server Metrics\')")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servermonitormetrics')
    # ### end Alembic commands ###
