def menu(profile=False,
         vms=False,
         recentchanges=False,
         documentation=False,
         faq=False,
         benchmarks=False,
         exampleresults=False,
         leaderboard=False,
         testruns=False,
         rawdata=False,
         feedback=False):
    return [
        ["Profile", "home", "/profile", profile],
        ["VMs", "layers", "/vms", vms],
        ["Recent changes", "layers", "/recentchanges", recentchanges],
        ["Documentation", "layers", "/documentation", documentation],
        #["Example results", "layers", "/exampleresults", exampleresults],
        ["FAQ", "layers", "/faq", faq],
        ["Leaderboard", "layers", "/leaderboard", leaderboard],
        ["Benchmarks", "layers", "/benchmarks", benchmarks],
        #["System status", "layers", "/systemstatus", system_status],
        #["Test runs", "layers", "/testruns", testruns],
        ["Datasets", "rawdata", "/rawdata", rawdata],
        ["Feedback", "layers", "/feedback", feedback]]
